[2023-12-01T23:32:33.695+0000] {processor.py:157} INFO - Started process (PID=1390) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:33.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:32:33.697+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:32:33.696+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:34.222+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:32:34.216+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/process_pubsub_message.py", line 54, in <module>
    retrieve_pubsub_messages_to_xcom()
  File "/opt/airflow/dags/process_pubsub_message.py", line 13, in retrieve_pubsub_messages_to_xcom
    subscriber = pubsub_v1.SubscriberClient()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/pubsub_v1/subscriber/client.py", line 81, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/client.py", line 496, in __init__
    self._transport = Transport(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/transports/grpc.py", line 155, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/transports/base.py", line 104, in __init__
    credentials, _ = google.auth.default(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 650, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 270, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 114, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File ..\config\credentials.json was not found.
[2023-12-01T23:32:34.222+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:34.237+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.544 seconds
[2023-12-01T23:32:34.705+0000] {processor.py:157} INFO - Started process (PID=1395) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:34.706+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:32:34.707+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:32:34.706+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:34.861+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:32:34.856+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/process_pubsub_message.py", line 54, in <module>
    retrieve_pubsub_messages_to_xcom()
  File "/opt/airflow/dags/process_pubsub_message.py", line 13, in retrieve_pubsub_messages_to_xcom
    subscriber = pubsub_v1.SubscriberClient()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/pubsub_v1/subscriber/client.py", line 81, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/client.py", line 496, in __init__
    self._transport = Transport(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/transports/grpc.py", line 155, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/transports/base.py", line 104, in __init__
    credentials, _ = google.auth.default(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 650, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 270, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 114, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File ..\config\credentials.json was not found.
[2023-12-01T23:32:34.862+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:34.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.176 seconds
[2023-12-01T23:32:56.845+0000] {processor.py:157} INFO - Started process (PID=1400) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:56.846+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:32:56.848+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:32:56.847+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:57.006+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:32:57.001+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/process_pubsub_message.py", line 54, in <module>
    retrieve_pubsub_messages_to_xcom()
  File "/opt/airflow/dags/process_pubsub_message.py", line 13, in retrieve_pubsub_messages_to_xcom
    subscriber = pubsub_v1.SubscriberClient()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/pubsub_v1/subscriber/client.py", line 81, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/client.py", line 496, in __init__
    self._transport = Transport(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/transports/grpc.py", line 155, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/transports/base.py", line 104, in __init__
    credentials, _ = google.auth.default(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 650, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 270, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 114, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File C:\Users\rober\Documents\DevsMentoring\_DevsMentoring_\Python\airflow\docker-implementation\config\credentials.json was not found.
[2023-12-01T23:32:57.006+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:32:57.024+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.182 seconds
[2023-12-01T23:33:27.245+0000] {processor.py:157} INFO - Started process (PID=1417) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:27.246+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:33:27.247+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:27.247+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:27.369+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:27.364+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/process_pubsub_message.py", line 54, in <module>
    retrieve_pubsub_messages_to_xcom()
  File "/opt/airflow/dags/process_pubsub_message.py", line 13, in retrieve_pubsub_messages_to_xcom
    subscriber = pubsub_v1.SubscriberClient()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/pubsub_v1/subscriber/client.py", line 81, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/client.py", line 496, in __init__
    self._transport = Transport(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/transports/grpc.py", line 155, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/pubsub_v1/services/subscriber/transports/base.py", line 104, in __init__
    credentials, _ = google.auth.default(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 650, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 270, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_default.py", line 114, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File C:\Users\rober\Documents\DevsMentoring\_DevsMentoring_\Python\airflow\docker-implementation\config\credentials.json was not found.
[2023-12-01T23:33:27.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:27.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.144 seconds
[2023-12-01T23:33:43.406+0000] {processor.py:157} INFO - Started process (PID=1434) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:43.407+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:33:43.408+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:43.407+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:43.537+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:43.533+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/process_pubsub_message.py", line 56, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2023-12-01T23:33:43.538+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:43.551+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.147 seconds
[2023-12-01T23:33:49.540+0000] {processor.py:157} INFO - Started process (PID=1439) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:49.541+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:33:49.542+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:49.541+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:49.670+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:50.131+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:50.131+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-01T23:33:50.141+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:50.141+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-01T23:33:50.147+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:50.147+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-01T23:33:50.148+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:50.148+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:33:50.160+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:50.160+0000] {dag.py:2963} INFO - Creating ORM DAG for pubsub_pandas_dag
[2023-12-01T23:33:50.169+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:50.169+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-11-30T23:33:50.169336+00:00, run_after=2023-12-01T23:33:50.169336+00:00
[2023-12-01T23:33:50.186+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.648 seconds
[2023-12-01T23:33:55.271+0000] {processor.py:157} INFO - Started process (PID=1444) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:55.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:33:55.273+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:55.272+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:55.419+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:33:55.428+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:55.428+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:33:55.454+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:33:55.454+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-11-30T23:33:55.453923+00:00, run_after=2023-12-01T23:33:55.453923+00:00
[2023-12-01T23:33:55.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.334 seconds
[2023-12-01T23:34:25.841+0000] {processor.py:157} INFO - Started process (PID=1465) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:34:25.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:34:25.843+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:34:25.843+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:34:25.984+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:34:26.006+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:34:26.004+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:34:26.144+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:34:26.144+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:34:26.158+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.320 seconds
[2023-12-01T23:34:56.260+0000] {processor.py:157} INFO - Started process (PID=1483) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:34:56.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:34:56.262+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:34:56.262+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:34:56.395+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:34:56.417+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:34:56.417+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:34:56.436+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:34:56.436+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:34:56.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.206 seconds
[2023-12-01T23:35:21.435+0000] {processor.py:157} INFO - Started process (PID=1500) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:21.436+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:35:21.437+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:21.437+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:21.588+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:21.613+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:21.613+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:35:21.633+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:21.633+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:35:21.654+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.221 seconds
[2023-12-01T23:35:27.578+0000] {processor.py:157} INFO - Started process (PID=1505) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:27.579+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:35:27.580+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:27.580+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:27.738+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:27.758+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:27.758+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:35:27.776+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:27.776+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:35:27.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.221 seconds
[2023-12-01T23:35:58.020+0000] {processor.py:157} INFO - Started process (PID=1525) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:58.021+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:35:58.022+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:58.021+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:58.133+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:35:58.150+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:58.150+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:35:58.167+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:35:58.167+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:35:58.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.279 seconds
[2023-12-01T23:36:29.243+0000] {processor.py:157} INFO - Started process (PID=1542) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:36:29.244+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:36:29.245+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:36:29.244+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:36:29.365+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:36:29.386+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:36:29.385+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:36:29.548+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:36:29.548+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:36:29.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.323 seconds
[2023-12-01T23:37:00.490+0000] {processor.py:157} INFO - Started process (PID=1559) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:37:00.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:37:00.492+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:37:00.492+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:37:00.613+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:37:00.631+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:37:00.631+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:37:00.761+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:37:00.761+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:37:00.776+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.288 seconds
[2023-12-01T23:37:31.771+0000] {processor.py:157} INFO - Started process (PID=1583) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:37:31.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:37:31.772+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:37:31.772+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:37:31.889+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:37:31.908+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:37:31.907+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:37:31.925+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:37:31.925+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:37:31.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.170 seconds
[2023-12-01T23:38:02.162+0000] {processor.py:157} INFO - Started process (PID=1600) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:02.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:38:02.165+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:02.164+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:02.287+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:02.305+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:02.305+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:38:02.322+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:02.322+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:38:02.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.178 seconds
[2023-12-01T23:38:03.193+0000] {processor.py:157} INFO - Started process (PID=1605) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:03.194+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:38:03.194+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:03.194+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:03.358+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:03.378+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:03.377+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:38:03.397+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:03.396+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:38:03.424+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.234 seconds
[2023-12-01T23:38:33.646+0000] {processor.py:157} INFO - Started process (PID=1642) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:33.647+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:38:33.648+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:33.648+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:33.767+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:38:33.785+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:33.784+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:38:33.802+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:38:33.802+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:38:33.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.176 seconds
[2023-12-01T23:39:03.878+0000] {processor.py:157} INFO - Started process (PID=1699) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:03.879+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:39:03.880+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:39:03.880+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:03.999+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:04.017+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:39:04.017+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:39:04.035+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:39:04.034+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:33:55.453923+00:00, run_after=2023-12-02T23:33:55.453923+00:00
[2023-12-01T23:39:04.157+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.281 seconds
[2023-12-01T23:39:15.042+0000] {processor.py:157} INFO - Started process (PID=1709) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:15.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:39:15.044+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:39:15.043+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:15.177+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:39:15.176+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:39:15.178+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:15.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.151 seconds
[2023-12-01T23:39:45.398+0000] {processor.py:157} INFO - Started process (PID=1726) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:45.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:39:45.400+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:39:45.400+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:45.520+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:39:45.519+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:39:45.521+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:39:45.534+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.138 seconds
[2023-12-01T23:40:15.740+0000] {processor.py:157} INFO - Started process (PID=1743) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:40:15.741+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:40:15.741+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:40:15.741+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:40:15.868+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:40:15.867+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:40:15.868+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:40:15.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.147 seconds
[2023-12-01T23:40:45.973+0000] {processor.py:157} INFO - Started process (PID=1761) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:40:45.974+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:40:45.974+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:40:45.974+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:40:46.079+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:40:46.078+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:40:46.079+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:40:46.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.121 seconds
[2023-12-01T23:41:16.286+0000] {processor.py:157} INFO - Started process (PID=1778) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:41:16.287+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:41:16.288+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:41:16.287+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:41:16.410+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:41:16.409+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:41:16.410+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:41:16.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.141 seconds
[2023-12-01T23:41:46.614+0000] {processor.py:157} INFO - Started process (PID=1795) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:41:46.615+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:41:46.616+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:41:46.616+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:41:46.727+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:41:46.726+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:41:46.728+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:41:46.739+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.128 seconds
[2023-12-01T23:42:16.812+0000] {processor.py:157} INFO - Started process (PID=1812) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:42:16.813+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:42:16.814+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:42:16.814+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:42:16.923+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:42:16.922+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:42:16.923+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:42:16.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.126 seconds
[2023-12-01T23:42:47.146+0000] {processor.py:157} INFO - Started process (PID=1829) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:42:47.147+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:42:47.147+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:42:47.147+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:42:47.262+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:42:47.261+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:42:47.262+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:42:47.275+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.132 seconds
[2023-12-01T23:43:17.464+0000] {processor.py:157} INFO - Started process (PID=1846) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:43:17.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:43:17.466+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:43:17.466+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:43:17.578+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:43:17.577+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:43:17.578+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:43:17.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.132 seconds
[2023-12-01T23:43:47.781+0000] {processor.py:157} INFO - Started process (PID=1863) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:43:47.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:43:47.783+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:43:47.782+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:43:47.892+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:43:47.891+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:43:47.892+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:43:47.904+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.125 seconds
[2023-12-01T23:44:17.977+0000] {processor.py:157} INFO - Started process (PID=1880) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:44:17.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:44:17.979+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:44:17.978+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:44:18.102+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:44:18.101+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:44:18.103+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:44:18.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.142 seconds
[2023-12-01T23:45:18.872+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:45:18.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:45:18.874+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:45:18.874+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:45:19.231+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:45:19.230+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:45:19.231+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:45:19.244+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.376 seconds
[2023-12-01T23:45:49.364+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:45:49.364+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:45:49.365+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:45:49.365+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:45:49.483+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:45:49.483+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:45:49.484+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:45:49.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.135 seconds
[2023-12-01T23:46:19.659+0000] {processor.py:157} INFO - Started process (PID=206) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:46:19.660+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:46:19.660+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:46:19.660+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:46:19.775+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:46:19.774+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:46:19.775+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:46:19.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.131 seconds
[2023-12-01T23:46:49.958+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:46:49.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:46:49.959+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:46:49.959+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:46:50.079+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:46:50.078+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:46:50.080+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:46:50.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.138 seconds
[2023-12-01T23:47:20.264+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:47:20.265+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:47:20.266+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:47:20.266+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:47:20.385+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:47:20.384+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:47:20.386+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:47:20.399+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.138 seconds
[2023-12-01T23:47:50.570+0000] {processor.py:157} INFO - Started process (PID=257) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:47:50.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:47:50.571+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:47:50.571+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:47:50.689+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:47:50.688+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:47:50.690+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:47:50.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.134 seconds
[2023-12-01T23:48:20.871+0000] {processor.py:157} INFO - Started process (PID=274) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:48:20.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:48:20.873+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:48:20.873+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:48:20.991+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:48:20.990+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:48:20.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:48:21.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.136 seconds
[2023-12-01T23:48:51.175+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:48:51.176+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:48:51.177+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:48:51.177+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:48:51.295+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:48:51.294+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:48:51.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:48:51.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.136 seconds
[2023-12-01T23:49:21.494+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:49:21.495+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:49:21.496+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:49:21.496+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:49:21.610+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:49:21.608+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:49:21.610+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:49:21.625+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.134 seconds
[2023-12-01T23:49:51.846+0000] {processor.py:157} INFO - Started process (PID=325) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:49:51.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:49:51.848+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:49:51.848+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:49:51.968+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:49:51.967+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:49:51.969+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:49:51.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.138 seconds
[2023-12-01T23:50:22.185+0000] {processor.py:157} INFO - Started process (PID=342) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:50:22.186+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:50:22.186+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:50:22.186+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:50:22.299+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:50:22.298+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:50:22.300+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:50:22.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.130 seconds
[2023-12-01T23:50:52.491+0000] {processor.py:157} INFO - Started process (PID=359) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:50:52.492+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:50:52.494+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:50:52.494+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:50:52.607+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:50:52.607+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:50:52.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:50:52.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.133 seconds
[2023-12-01T23:51:22.798+0000] {processor.py:157} INFO - Started process (PID=376) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:51:22.799+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:51:22.801+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:51:22.800+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:51:22.918+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:51:22.916+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:51:22.918+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:51:22.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.136 seconds
[2023-12-01T23:51:53.108+0000] {processor.py:157} INFO - Started process (PID=393) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:51:53.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:51:53.110+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:51:53.110+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:51:53.237+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:51:53.236+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/process_pubsub_message.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: pubsub_pandas_dag. Faulty task: retrieve_messages
[2023-12-01T23:51:53.237+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:51:53.250+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.144 seconds
[2023-12-01T23:52:14.378+0000] {processor.py:157} INFO - Started process (PID=410) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:52:14.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:52:14.380+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:14.380+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:52:14.508+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:52:14.583+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:14.582+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-01T23:52:14.591+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:14.591+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-01T23:52:14.597+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:14.597+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-01T23:52:14.598+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:14.597+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:52:14.730+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:14.729+0000] {dag.py:2963} INFO - Creating ORM DAG for pubsub_pandas_dag
[2023-12-01T23:52:14.739+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:14.739+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-11-30T23:52:14.739096+00:00, run_after=2023-12-01T23:52:14.739096+00:00
[2023-12-01T23:52:14.760+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.384 seconds
[2023-12-01T23:52:45.600+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:52:45.601+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:52:45.602+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:45.602+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:52:45.708+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:52:45.725+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:45.725+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:52:45.742+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:52:45.742+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-11-30T23:52:45.742410+00:00, run_after=2023-12-01T23:52:45.742410+00:00
[2023-12-01T23:52:45.757+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.158 seconds
[2023-12-01T23:53:15.950+0000] {processor.py:157} INFO - Started process (PID=444) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:53:15.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:53:15.951+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:53:15.951+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:53:16.060+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:53:16.077+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:53:16.077+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:53:16.095+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:53:16.094+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-11-30T23:53:16.094675+00:00, run_after=2023-12-01T23:53:16.094675+00:00
[2023-12-01T23:53:16.109+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.161 seconds
[2023-12-01T23:53:46.315+0000] {processor.py:157} INFO - Started process (PID=461) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:53:46.316+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:53:46.317+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:53:46.317+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:53:46.435+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:53:46.457+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:53:46.457+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:53:46.478+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:53:46.478+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-11-30T23:53:46.478341+00:00, run_after=2023-12-01T23:53:46.478341+00:00
[2023-12-01T23:53:46.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.180 seconds
[2023-12-01T23:54:16.626+0000] {processor.py:157} INFO - Started process (PID=518) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:54:16.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:54:16.629+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:54:16.628+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:54:16.766+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:54:16.788+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:54:16.788+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:54:16.806+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:54:16.806+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:54:16.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.199 seconds
[2023-12-01T23:54:46.913+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:54:46.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:54:46.915+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:54:46.914+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:54:47.018+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:54:47.039+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:54:47.039+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:54:47.055+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:54:47.055+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:54:47.072+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.161 seconds
[2023-12-01T23:55:17.182+0000] {processor.py:157} INFO - Started process (PID=552) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:55:17.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:55:17.183+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:55:17.183+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:55:17.283+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:55:17.303+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:55:17.302+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:55:17.320+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:55:17.320+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:55:17.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.156 seconds
[2023-12-01T23:55:47.410+0000] {processor.py:157} INFO - Started process (PID=569) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:55:47.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:55:47.412+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:55:47.411+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:55:47.523+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:55:47.544+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:55:47.543+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:55:47.562+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:55:47.562+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:55:47.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.169 seconds
[2023-12-01T23:56:17.677+0000] {processor.py:157} INFO - Started process (PID=586) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:56:17.678+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:56:17.679+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:56:17.679+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:56:17.786+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:56:17.806+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:56:17.805+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:56:17.823+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:56:17.823+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:56:17.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.163 seconds
[2023-12-01T23:56:47.940+0000] {processor.py:157} INFO - Started process (PID=603) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:56:47.941+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:56:47.941+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:56:47.941+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:56:48.052+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:56:48.071+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:56:48.070+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:56:48.087+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:56:48.087+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:56:48.101+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.164 seconds
[2023-12-01T23:57:18.300+0000] {processor.py:157} INFO - Started process (PID=620) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:57:18.301+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:57:18.302+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:57:18.301+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:57:18.407+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:57:18.426+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:57:18.425+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:57:18.442+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:57:18.442+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:57:18.457+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.159 seconds
[2023-12-01T23:57:48.501+0000] {processor.py:157} INFO - Started process (PID=637) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:57:48.502+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:57:48.502+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:57:48.502+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:57:48.607+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:57:48.625+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:57:48.625+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:57:48.642+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:57:48.642+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:57:48.659+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.161 seconds
[2023-12-01T23:58:18.860+0000] {processor.py:157} INFO - Started process (PID=654) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:58:18.862+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:58:18.862+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:58:18.862+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:58:18.971+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:58:18.989+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:58:18.988+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:58:19.006+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:58:19.006+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:58:19.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.163 seconds
[2023-12-01T23:58:49.058+0000] {processor.py:157} INFO - Started process (PID=671) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:58:49.059+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:58:49.060+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:58:49.060+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:58:49.171+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:58:49.189+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:58:49.188+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:58:49.207+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:58:49.206+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:58:49.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.165 seconds
[2023-12-01T23:59:19.318+0000] {processor.py:157} INFO - Started process (PID=728) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:59:19.319+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:59:19.320+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:59:19.319+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:59:19.428+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:59:19.450+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:59:19.449+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:59:19.466+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:59:19.466+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:59:19.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.165 seconds
[2023-12-01T23:59:49.694+0000] {processor.py:157} INFO - Started process (PID=745) to work on /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:59:49.695+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/process_pubsub_message.py for tasks to queue
[2023-12-01T23:59:49.695+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:59:49.695+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:59:49.805+0000] {processor.py:839} INFO - DAG(s) dict_keys(['pubsub_pandas_dag']) retrieved from /opt/airflow/dags/process_pubsub_message.py
[2023-12-01T23:59:49.822+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:59:49.822+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-01T23:59:49.839+0000] {logging_mixin.py:154} INFO - [2023-12-01T23:59:49.839+0000] {dag.py:3722} INFO - Setting next_dagrun for pubsub_pandas_dag to 2023-12-01T23:53:46.478341+00:00, run_after=2023-12-02T23:53:46.478341+00:00
[2023-12-01T23:59:49.855+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/process_pubsub_message.py took 0.163 seconds
